import 'dart:convert';
import 'package:http/http.dart' as http;

class Autogenerated {
  int? userId;
  int? id;
  String? title;
  String? body;

  Autogenerated({this.userId, this.id, this.title, this.body});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
      body: json['body'],
    );
  }
}

Future<List<Autogenerated>> fetchData() async {
  final response = await http.get(Uri.parse('https://jsonplaceholder.typicode.com/posts'));
  if (response.statusCode == 200) {
    List<dynamic> jsonResponse = json.decode(response.body);
    return jsonResponse.map((data) => Autogenerated.fromJson(data)).toList();
  } else {
    throw Exception('Failed to load data');
  }
}
